nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@react-spring/core@*":
    peerDependenciesMeta:
      react:
        optional: true
  "@react-spring/konva@*":
    peerDependenciesMeta:
      konva:
        optional: true
      react:
        optional: true
      react-konva:
        optional: true
  "@react-spring/native@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-native:
        optional: true
  "@react-spring/three@*":
    peerDependenciesMeta:
      "@react-three/fiber":
        optional: true
      react:
        optional: true
      three:
        optional: true
  "@react-spring/web@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@react-spring/zdog@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      react-zdog:
        optional: true
      zdog:
        optional: true
  antd@*:
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  eslint-config-react-app@*:
    peerDependenciesMeta:
      babel-eslint:
        optional: true
  eslint-utils@*:
    peerDependenciesMeta:
      eslint:
        optional: true
  fork-ts-checker-webpack-plugin@*:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  postcss-loader@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  postcss-scss@*:
    peerDependenciesMeta:
      postcss:
        optional: true
  ts-node@*:
    peerDependenciesMeta:
      typescript:
        optional: true

yarnPath: .yarn/releases/yarn-3.1.1.cjs
