nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  next-pwa@*:
    dependencies:
      "@babel/core": "*"
      webpack: "*"
  next-sitemap@*:
    peerDependenciesMeta:
      "@next/env":
        optional: true
  stylelint-config-recommended-scss@*:
    dependencies:
      postcss: "*"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
